# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lancedb_search.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lancedb_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14lancedb_search.proto\x12\x0eoci.lancedb.v1\"=\n\rSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\r\x12\r\n\x05where\x18\x03 \x01(\t\".\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nsource_uri\x18\x02 \x01(\t\"N\n\x0eSearchResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.oci.lancedb.v1.SearchResult\x12\r\n\x05\x63ount\x18\x02 \x01(\r2V\n\x0bLanceSearch\x12G\n\x06Search\x12\x1d.oci.lancedb.v1.SearchRequest\x1a\x1e.oci.lancedb.v1.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lancedb_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=40
  _globals['_SEARCHREQUEST']._serialized_end=101
  _globals['_SEARCHRESULT']._serialized_start=103
  _globals['_SEARCHRESULT']._serialized_end=149
  _globals['_SEARCHRESPONSE']._serialized_start=151
  _globals['_SEARCHRESPONSE']._serialized_end=229
  _globals['_LANCESEARCH']._serialized_start=231
  _globals['_LANCESEARCH']._serialized_end=317
# @@protoc_insertion_point(module_scope)
